nav:
  Home: /
  # About: /about/
  Writing: /archives/
  Projects: https://github.com/JensenJiang

projects_url: http://github.com/probberechts

customize:
    gravatar:
        email: jensenjiang1995@gmail.com
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with lttp://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/probberechts/cactus-dark
        twitter: https://twitter.com/JensenJiang1995
        # facebook: /
        # linkedin: /
    show_all_posts: false
    post_count: 10
    highlight: rainbow

# RSS
rss:

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-86660611-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:

# MathJax
mathjax:
  enable: true
  per_page: true
  cdn: "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
